spring:
  application:
    name: zuul-gateway
zuul:
  routes:
    colours:
      path: /colours/**
      serviceId: colours-service
    characters:
      path: /characters/**
      serviceId: characters-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka